export { default as Callout } from "./Callout.vue";
export { default as Color } from "./Color.vue";
export { default as Colors } from "./Colors.vue";
export { default as ColorThemable } from "./ColorThemable.vue";
export { default as ComponentPreview } from "./ComponentPreview.vue";
export { default as DataAttributesTable } from "./tables/DataAttributesTable.vue";
export { default as EmitsTable } from "./tables/EmitsTable.vue";
export { default as LandingPage } from "./LandingPage.vue";
export { default as LinkCard } from "./LinkCard.vue";
export { default as LinkedCard } from "./LinkedCard.vue";
export { default as Logomark } from "./Logomark.vue";
export { default as PropsTable } from "./tables/PropsTable.vue";
export { default as SlotsTable } from "./tables/SlotsTable.vue";
export { default as Steps } from "./Steps.vue";
export { default as TabMarkdown } from "./TabMarkdown.vue";
export { default as TabPreview } from "./TabPreview.vue";
export { default as TabsMarkdown } from "./TabsMarkdown.vue";
export { default as VPImage } from "./VPImage.vue";

export { Alert, Tabs, TabsContent, TabsList, TabsTrigger } from "wedges-vue";
